const soma = Number(process.argv[2]) + Number(process.argv[3])
console.log(soma)
const sub = Number(process.argv[2]) - Number(process.argv[3])
console.log(sub)
const mult = Number(process.argv[2]) * Number(process.argv[3])
console.log(mult)
const div = Number(process.argv[2]) / Number(process.argv[3])
console.log(div)
